version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: ''
      VERSION: '2.9.1'
      MAINTAINER: "PBRP Team"
      VENDOR: 'xiaomi'
      CODENAME: 'wayne'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: 'true'
      # EXTRA_CMD: ""
      # PB_ENGLISH: 'true'
      CHANGELOG: |
        - Initial build
          - Based on Official TWRP
        - What's been done?
          - Implemented System-As-Root
          - Added logcat, NTFS & ExFAT support
          - Implemented cryptfs_hw encryption support
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0-dev'
          context: org-global
